name = "BRAL"
version = "0.1.0"
defaultTargets = ["bral"]

[[lean_lib]]
name = "BRAL"

[[lean_exe]]
name = "bral"
root = "Main"


[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.24.0"